name: osx-ubuntu-manual-install

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env: 
      EXP_CONDA_VER: 4.8.3
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: macos-latest
          PLATFORM: MacOSX-x86_64
          SOURCE_SCRIPT: /Users/runner/miniconda-4.8.3/etc/profile.d/conda.sh
        - os: ubuntu-latest
          PLATFORM: Linux-x86_64
          SOURCE_SCRIPT: /home/runner/miniconda-4.8.3/etc/profile.d/conda.sh

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install miniconda
      shell: bash -l {0}
      run: |
        source setup/setup_conda.sh $EXP_CONDA_VER ${{ matrix.PLATFORM }}
        if [ ${{ matrix.PLATFORM }} == "Linux-x86_64" ]; then
            echo "Linux install, going to check conda path"
            which conda
        else
            echo "OSX install, skipping conda path check"
            echo "    since 'which conda' inexplicably returns with status code 1"
            echo "    only in the CI environment"
        fi

    - name: Check whether the CI environment variable is set
      shell: bash -l {0}
      run: |
        echo $CI

    - name: Activate the newly setup conda
      shell: bash -l {0}
      run: |
        source setup/activate_conda.sh

    - name: Setup the environment
      shell: bash -l {0}
      run: |
        source setup/setup.sh

    - name: Activate the newly setup environment
      shell: bash -l {0}
      run: |
        source setup/activate.sh

    - name: Verify that we have an environment other than the base
      shell: bash -l {0}
      run: |
        source setup/activate.sh
        conda env list

    - name: Teardown the environment
      shell: bash -l {0}
      run: |
        source ${{ matrix.SOURCE_SCRIPT }}
        source setup/teardown.sh

    - name: Teardown the miniconda install
      shell: bash -l {0}
      run: |
        source setup/teardown_conda.sh $EXP_CONDA_VER

